name: Docker Image CI

on:
  push:
  
  workflow_dispatch: #permet de lancer le workflow manuellement pour voir si ca marche

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2 #se connecter au docker hub
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
     

    - name: Build the Docker image
      run: |
        docker build . -t nzeketa/efrei-devops-tp2:0.0.1
        docker push nzeketa/efrei-devops-tp2:0.0.1
